############
# starship #
############

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = true
# format = '''$jobs$shell$memory_usage$hostname$username$directory$status$character'''
# right_format = '''$all'''
palette = "catppuccin_mocha"

[battery]
full_symbol = 'ó±Š£ '
charging_symbol = 'ó±Š¥ '
discharging_symbol = 'ó±Š¡ '
unknown_symbol = 'ó±ƒ '
empty_symbol = 'ó°‚ '
format = '\[[$symbol$percentage]($style)\] '
[[battery.display]]
threshold = 10
style = 'bold red'
[[battery.display]]
threshold = 20
style = 'bold yellow'
[[battery.display]]
threshold = 30
style = 'bold'

[character]
success_symbol = '[ï”](bold green)' # nf-fa-chevron_right
error_symbol = '[ï”](bold red)'     # nf-fa-chevron_up
vimcmd_symbol = '[ï“](bold purple)' # nf-fa-chevron_left

[cmd_duration]
format = '\[[ï”  $duration]($style)\] ' # nf-fa-stopwatch
show_notifications = false
notification_timeout = 2_000

[directory]
format = '[$read_only ]($read_only_style)[$path]($style) '
read_only = " ó°Œ¾"
read_only_style = 'bold red'
before_repo_root_style = 'bold grey'
repo_root_style = 'bold green'
repo_root_format = '[$read_only ]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) '
fish_style_pwd_dir_length = 1

[hostname]
format = '\[[$ssh_symbol$hostname]($style)\] '
ssh_symbol = "î¬ "

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\] '
symbol = "ó°› "

[shell]
disabled = false
zsh_indicator = ''

[shlvl]
# disabled = false
threshold = 3
format = '\[[$symbol$shlvl]($style)\] '
symbol = 'ï½'

[status]
disabled = false
map_symbol = true
pipestatus = true
format = '[\[$symbol $status\]]($style)'
symbol = 'ï€'                             # nf-fa-times
success_symbol = ''
not_executable_symbol = 'ï„ª'              # nf-fa-exclamation
not_found_symbol = 'ï€‚'                   # nf-fa-search
sigint_symbol = 'ó°Ÿ¾'                      # nf-md-wall
signal_symbol = 'ïƒ§'                      # nf-fa-bolt

[time]
disabled = false
format = ' [$time]($style) '
time_format = '%H:%M'

[username]
# format = '[$user]($style)@'
# format = '\[[$user]($style)\] '

######################
#     nerd-fonts     #
# bracketed-segments #
######################

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\] )]($style)\] '
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[bun]
format = '\[[$symbol($version)]($style)\] '

[c]
format = '\[[$symbol($version(-$name))]($style)\] '
symbol = "î˜ "

[cmake]
format = '\[[$symbol($version)]($style)\] '

# [cmd_duration]
# format = '\[[ï”  $duration]($style)\] '

[cobol]
format = '\[[$symbol($version)]($style)\] '

[conda]
format = '\[[$symbol$environment]($style)\] '
symbol = "ï„Œ "

[crystal]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜¯ "

[daml]
format = '\[[$symbol($version)]($style)\] '

[dart]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜ "

[deno]
format = '\[[$symbol($version)]($style)\] '

# [directory]
# read_only = " ó°Œ¾"

[docker_context]
format = '\[[$symbol$context]($style)\] '
symbol = "ïŒˆ "

[dotnet]
format = '\[[$symbol($version)(ğŸ¯ $tfm)]($style)\] '

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\] '
symbol = "î˜­ "

[elm]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜¬ "

[erlang]
format = '\[[$symbol($version)]($style)\] '

[fennel]
format = '\[[$symbol($version)]($style)\] '
symbol = "îš¯ "

[fossil_branch]
format = '\[[$symbol$branch]($style)\] '
symbol = "ï˜ "

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\] '

[git_branch]
format = '\[[$symbol$branch]($style)\] '
symbol = "ï˜ "

[git_commit]
format = '[\($hash$tag\)]($style) '
style = 'bold yellow'
tag_symbol = 'ï€« '

[git_metrics]
disabled = false
only_nonzero_diffs = true
format = '\[[+$added]($added_style)/[-$deleted]($deleted_style)\] '

[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
conflicted = 'î‰¹ '                                    # nf-fae-equal
ahead = 'ï¢'                                          # nf-fa-arrow_up
behind = 'ï£'                                         # nf-fa-arrow_down
diverged = 'ï¢ï£'                                      # nf-fa-arrows_v nf-fa-long_arrow_up nf-fa-long_arrow_down
up_to_date = ''
untracked = 'ï„¨'                                      # nf-fa-question
stashed = 'ï…•'                                        # nf-fa-dollar
modified = 'ï„ª'                                       # nf-fa-exclamation
staged = 'ï§'                                         # nf-fa-plus
renamed = 'ïŠ’ '                                       # nf-fa-hashtag
deleted = 'ï€'                                        # nf-fa-times
typechanged = 'ï©'                                    # nf-fa-asterisk

[golang]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜§ "

[gradle]
format = '\[[$symbol($version)]($style)\] '

[guix_shell]
format = '\[[$symbol]($style)\] '
symbol = "ïŒ¥ "

[haskell]
format = '\[[$symbol($version)]($style)\] '
symbol = "î· "

[haxe]
format = '\[[$symbol($version)]($style)\] '
symbol = "î™¦ "

[helm]
format = '\[[$symbol($version)]($style)\] '

[hg_branch]
format = '\[[$symbol$branch]($style)\] '
symbol = "ï˜ "

# [hostname]
# ssh_symbol = "î¬ "

[java]
format = '\[[$symbol($version)]($style)\] '
symbol = "î‰– "

[julia]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜¤ "

[kotlin]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜´ "

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\] '

[lua]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜  "

# [memory_usage]
# format = '\[$symbol[$ram( | $swap)]($style)\] '
# symbol = "ó°› "

[meson]
format = '\[[$symbol$project]($style)\] '
symbol = "ó°”· "

[nim]
format = '\[[$symbol($version)]($style)\] '
symbol = "ó°†¥ "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\] '
symbol = "ïŒ“ "

[nodejs]
format = '\[[$symbol($version)]($style)\] '
symbol = "îœ˜ "

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\] '
symbol = "î™º "

[opa]
format = '\[[$symbol($version)]($style)\] '

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\] '

[os]
format = '\[[$symbol]($style)\] '

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
format = '\[[$symbol$version]($style)\] '
symbol = "ó°— "

[perl]
format = '\[[$symbol($version)]($style)\] '
symbol = "î™¾ "

[php]
format = '\[[$symbol($version)]($style)\] '
symbol = "î˜ˆ "

[pijul_channel]
format = '\[[$symbol$channel]($style)\] '
symbol = "ï˜ "

[pulumi]
format = '\[[$symbol$stack]($style)\] '

[purescript]
format = '\[[$symbol($version)]($style)\] '

[python]
symbol = "îˆµ "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\] '

[red]
format = '\[[$symbol($version)]($style)\] '

[rlang]
symbol = "ó°Ÿ” "

[ruby]
format = '\[[$symbol($version)]($style)\] '
symbol = "î‘ "

[rust]
format = '\[[$symbol($version)]($style)\] '
symbol = "î¨ "

[scala]
format = '\[[$symbol($version)]($style)\] '
symbol = "îœ· "

[spack]
format = '\[[$symbol$environment]($style)\] '

[sudo]
format = '\[[as $symbol]($style)\] '

[swift]
format = '\[[$symbol($version)]($style)\] '
symbol = "î• "

[terraform]
format = '\[[$symbol$workspace]($style)\] '

# [time]
# format = '\[[$time]($style)\] '

# [username]
# format = '\[[$user]($style)\] '

[vagrant]
format = '\[[$symbol($version)]($style)\] '

[vlang]
format = '\[[$symbol($version)]($style)\] '

[zig]
format = '\[[$symbol($version)]($style)\] '
symbol = "îš© "

[solidity]
format = '\[[$symbol($version)]($style)\] '


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
